export type Language = 'en' | 'ar';
export const copy = {
  en: {
    nav: { home: 'Home', about: 'About', experience: 'Experience', skills: 'Skills', projects: 'Projects', education: 'Education', contact: 'Contact', download: 'Download CV', menu: 'Open navigation menu', close: 'Close navigation menu', lightMode: 'Switch to light mode', darkMode: 'Switch to dark mode', lightTag: 'LIGHT', darkTag: 'DARK' },
    hero: { eyebrow: 'NAVIGATION SCIENCE & SPACE TECHNOLOGY', first: 'AHMED', last: 'ABDEL FATAH', role: 'Navigation Science & Space Technology Student', body: 'Exploring space technology, navigation systems, networking, and engineering applications.', journey: 'Explore my journey', contact: 'Get in touch', coordinates: '30° 47′ N  ·  31° 00′ E', visual: 'PROFILE IMAGE · REPLACEABLE' },
    about: { eyebrow: 'A LITTLE ABOUT ME', title: 'Curiosity, with a direction.', body: 'I am a Navigation Science and Space Technology student at Beni Suef University. My interests sit where space, navigation, communications, and practical engineering meet. I value careful learning, clear collaboration, and building a strong technical foundation.', label: 'AREAS OF INTEREST', chips: ['Space technology', 'Navigation', 'Communications', 'Networking', 'Engineering', 'Project management'], card: 'CURRENT FOCUS', cardTitle: 'Learning how systems connect', cardBody: 'From orbital applications to network fundamentals, I am building a broad, grounded view of technology.' },
    experience: { eyebrow: 'LEARNING IN PRACTICE', title: 'Training & experience', intro: 'A growing foundation shaped by training and exposure across space applications, management, and networking.', details: 'View details', trainingLabel: 'TRAINING', more: 'Training highlight', items: { esa: { organization: 'Egyptian Space Agency', category: 'Space / Environmental Applications', description: 'Training and learning experience related to environmental applications within space technology.', date: '' }, spaceKey: { organization: 'Space Key', category: 'Space Technology', description: 'Training and learning experience related to space technology and its applications.', date: '' }, bue: { organization: 'The British University in Egypt', category: 'Project Management', description: 'Project Management training focused on professional project planning and management concepts.', date: 'August 2024' }, we: { organization: 'WE', category: 'Networking', description: 'Networking training through the WE Training Sector, covering fundamental networking concepts and practical learning.', date: 'August 2025' } } },
    skills: { eyebrow: 'BUILDING MY TOOLKIT', title: 'Skills & foundations', intro: 'A snapshot of the subjects I am studying and developing. No proficiency scores, just an honest view of my current foundation.', learning: 'Learning', fundamentals: 'Fundamentals', trainingLevel: 'Training', familiar: 'Familiar', items: { navigation: 'Navigation science', space: 'Space technology', networking: 'Networking', communications: 'Communication systems', projectManagement: 'Project management', research: 'Technical research', engineering: 'Engineering principles', productivity: 'Microsoft Office & productivity' } },
    projects: { eyebrow: 'ACADEMIC EXPLORATION', title: 'Projects & academic work', intro: 'Areas of study and practice that reflect my interests. Specific project details will be added as completed work is ready to share.', details: 'View details', modalClose: 'Close details', modalLabel: 'AREA OVERVIEW', categories: { spaceNavigation: { title: 'Space technology & navigation', description: 'Academic and learning work related to navigation science and space technology.', detail: 'This category represents coursework and ongoing learning around navigation science and space technology. Individual work can be added here as it is completed and ready to share.' }, networkPractice: { title: 'Networking practice', description: 'Hands-on practice with networking concepts and network configuration.', detail: 'A space for practical networking exercises and configuration work. Add specific examples, tools, and outcomes here when you are ready to publish them.' }, projectWork: { title: 'Project management', description: 'Academic and training work related to project planning and management.', detail: 'A place to present project planning and management work. Specific project details have not been supplied yet.' }, spaceApplications: { title: 'Space applications', description: 'Exploration of practical applications of space technology.', detail: 'A space for learning related to real-world applications of space technology, including environmental applications.' } } },
    education: { eyebrow: 'ACADEMIC PATH', title: 'Education', university: 'Beni Suef University', faculty: 'Faculty of Navigation Science and Space Technology', program: 'Program', programName: 'Navigation Science and Space Technology', expected: 'Expected graduation', status: 'IN PROGRESS' },
    contact: { eyebrow: 'START A CONVERSATION', title: 'Let’s connect.', intro: 'Interested in technology, space, navigation, networking, or collaboration? Feel free to get in touch.', name: 'Name', email: 'Email', message: 'Message', send: 'Send message', sending: 'Sending…', note: 'The form sends through the configured contact service. It will show an error if setup is missing. You can also email me directly below.', linkedin: 'Connect on LinkedIn', emailLabel: 'Email me', validation: 'Please complete all fields with a valid email address.', sent: 'Your message was sent successfully. Thank you for reaching out.', notConfigured: 'The contact service is not configured yet. Please email me directly using the address below.', sendFailed: 'Your message could not be sent right now. Please try again or email me directly.' },
    footer: { rights: 'All rights reserved.', discipline: 'Navigation Science & Space Technology', top: 'Back to top', made: 'Thoughtfully learning, one system at a time.' },
    common: { open: 'Open', close: 'Close' },
  },
  ar: {
    nav: { home: 'الرئيسية', about: 'نبذة عني', experience: 'الخبرة والتدريب', skills: 'المهارات', projects: 'المشروعات', education: 'التعليم', contact: 'تواصل', download: 'تحميل السيرة الذاتية', menu: 'فتح قائمة التنقل', close: 'إغلاق قائمة التنقل', lightMode: 'التبديل إلى الوضع الفاتح', darkMode: 'التبديل إلى الوضع الداكن', lightTag: 'فاتح', darkTag: 'داكن' },
    hero: { eyebrow: 'علوم الملاحة وتكنولوجيا الفضاء', first: 'أحمد', last: 'عبدالفتاح', role: 'طالب علوم الملاحة وتكنولوجيا الفضاء', body: 'أستكشف تكنولوجيا الفضاء وأنظمة الملاحة والشبكات والتطبيقات الهندسية.', journey: 'اكتشف مسيرتي', contact: 'تواصل معي', coordinates: '٣٠° ٤٧′ شمالاً · ٣١° ٠٠′ شرقاً', visual: 'صورة شخصية · قابلة للاستبدال' },
    about: { eyebrow: 'نبذة بسيطة عني', title: 'فضول يقوده هدف.', body: 'أنا طالب علوم الملاحة وتكنولوجيا الفضاء بجامعة بني سويف. تتقاطع اهتماماتي بين الفضاء والملاحة والاتصالات والهندسة التطبيقية. أقدّر التعلم المتأني والتعاون الواضح وبناء أساس تقني قوي.', label: 'مجالات الاهتمام', chips: ['تكنولوجيا الفضاء', 'الملاحة', 'الاتصالات', 'الشبكات', 'الهندسة', 'إدارة المشروعات'], card: 'تركيزي الحالي', cardTitle: 'فهم ترابط الأنظمة', cardBody: 'من تطبيقات المدارات إلى أساسيات الشبكات، أبني فهماً واسعاً وعملياً للتكنولوجيا.' },
    experience: { eyebrow: 'التعلم بالتطبيق', title: 'التدريب والخبرة', intro: 'أساس يتطور من خلال التدريب والتعرف على تطبيقات الفضاء والإدارة والشبكات.', details: 'عرض التفاصيل', trainingLabel: 'تدريب', more: 'نبذة عن التدريب', items: { esa: { organization: 'وكالة الفضاء المصرية', category: 'تطبيقات الفضاء والبيئة', description: 'تجربة تدريبية وتعليمية مرتبطة بالتطبيقات البيئية ضمن تكنولوجيا الفضاء.', date: '' }, spaceKey: { organization: 'Space Key', category: 'تكنولوجيا الفضاء', description: 'تجربة تدريبية وتعليمية مرتبطة بتكنولوجيا الفضاء وتطبيقاتها.', date: '' }, bue: { organization: 'الجامعة البريطانية في مصر', category: 'إدارة المشروعات', description: 'تدريب في إدارة المشروعات ركز على مفاهيم التخطيط والإدارة المهنية.', date: 'أغسطس 2024' }, we: { organization: 'WE', category: 'الشبكات', description: 'تدريب عبر قطاع تدريب WE تناول أساسيات الشبكات ومفاهيمها العملية.', date: 'أغسطس 2025' } } },
    skills: { eyebrow: 'أبني أدواتي', title: 'المهارات والأساسيات', intro: 'لمحة عن الموضوعات التي أدرسها وأطورها. أعرض مستواي بصدق دون نسب إتقان غير دقيقة.', learning: 'قيد التعلم', fundamentals: 'أساسيات', trainingLevel: 'تدريب', familiar: 'إلمام', items: { navigation: 'علوم الملاحة', space: 'تكنولوجيا الفضاء', networking: 'الشبكات', communications: 'أنظمة الاتصالات', projectManagement: 'إدارة المشروعات', research: 'البحث التقني', engineering: 'مبادئ الهندسة', productivity: 'مايكروسوفت أوفيس وأدوات الإنتاجية' } },
    projects: { eyebrow: 'استكشاف أكاديمي', title: 'المشروعات والأعمال الأكاديمية', intro: 'مجالات للدراسة والتطبيق تعكس اهتماماتي. سأضيف تفاصيل المشروعات عند اكتمال أعمال قابلة للمشاركة.', details: 'عرض التفاصيل', modalClose: 'إغلاق التفاصيل', modalLabel: 'نبذة عن المجال', categories: { spaceNavigation: { title: 'تكنولوجيا الفضاء والملاحة', description: 'أعمال أكاديمية وتعليمية مرتبطة بعلوم الملاحة وتكنولوجيا الفضاء.', detail: 'يمثل هذا المجال المقررات والتعلم المستمر في علوم الملاحة وتكنولوجيا الفضاء. يمكن إضافة الأعمال الفردية عند اكتمالها واستعدادها للمشاركة.' }, networkPractice: { title: 'تطبيقات الشبكات', description: 'تدريب عملي على مفاهيم الشبكات وإعدادها.', detail: 'مساحة للتمارين العملية وإعداد الشبكات. يمكن إضافة أمثلة وأدوات ونتائج محددة عند الرغبة في نشرها.' }, projectWork: { title: 'إدارة المشروعات', description: 'أعمال أكاديمية وتدريبية في تخطيط المشروعات وإدارتها.', detail: 'مكان لعرض أعمال تخطيط المشروعات وإدارتها. لم يتم تزويدي بعد بتفاصيل مشروع محدد.' }, spaceApplications: { title: 'تطبيقات الفضاء', description: 'استكشاف التطبيقات العملية لتكنولوجيا الفضاء.', detail: 'مساحة للتعلم حول التطبيقات الواقعية لتكنولوجيا الفضاء، بما فيها التطبيقات البيئية.' } } },
    education: { eyebrow: 'المسار الأكاديمي', title: 'التعليم', university: 'جامعة بني سويف', faculty: 'كلية علوم الملاحة وتكنولوجيا الفضاء', program: 'البرنامج', programName: 'علوم الملاحة وتكنولوجيا الفضاء', expected: 'التخرج المتوقع', status: 'قيد الدراسة' },
    contact: { eyebrow: 'لنبدأ حواراً', title: 'يسعدني التواصل.', intro: 'هل تهتم بالتكنولوجيا أو الفضاء أو الملاحة أو الشبكات أو التعاون؟ يسعدني أن تراسلني.', name: 'الاسم', email: 'البريد الإلكتروني', message: 'الرسالة', send: 'إرسال الرسالة', sending: 'جارٍ الإرسال…', note: 'يرسل النموذج عبر خدمة التواصل بعد إعدادها، وستظهر رسالة خطأ إذا لم تكن مهيأة. ويمكنك مراسلتي مباشرة من الرابط أدناه.', linkedin: 'تواصل عبر لينكدإن', emailLabel: 'راسلني', validation: 'يرجى إكمال جميع الحقول وإدخال بريد إلكتروني صحيح.', sent: 'تم إرسال رسالتك بنجاح. شكراً لتواصلك.', notConfigured: 'خدمة إرسال الرسائل غير مهيأة بعد. يمكنك مراسلتي مباشرة عبر البريد أدناه.', sendFailed: 'تعذر إرسال رسالتك الآن. حاول مرة أخرى أو راسلني مباشرة.' },
    footer: { rights: 'جميع الحقوق محفوظة.', discipline: 'علوم الملاحة وتكنولوجيا الفضاء', top: 'العودة للأعلى', made: 'تعلم مستمر، نظاماً بعد نظام.' },
    common: { open: 'فتح', close: 'إغلاق' },
  },
} as const;

export type Copy = typeof copy.en;
